### ISSUE TITLE
Possible gramatical error

### ISSUE THREAD

**Issue by delos19** [SDSURocketProject/Git-Workshop#11]
The portion that references good and bad commits contains a grammatical spelling error:

- "# changed beep to [FOUR] seconds for overpressure"

While this may be a direct quote, from the reader's perspective it was a bit confusing to read/comprehend.

Suggestions:

- Add corrected bracketed spelling
- Replace current good example of commit with alternative example

**Comment by delos19** [comment]
I'm reading this on our current git, I am not sure if this is depreciated as we switched to gitlab but submitted the issue as such.

**Comment by alefir** [comment]
Yeah, it's an error from when I copied over the commit messages since I typed instead of copying and pasting.

This repo isn't used anymore since we switched to gitlab ([equivalent repo here](https://git.sdsurocketproject.org/avionics/git-workshop)) and I'll fix the problem over there.
